const { generatorHandler } = require('@prisma/generator-helper')
const fs = require('node:fs')
const path = require('node:path')

const PRISMA_TO_TS = {
  String: 'string',
  Int: 'number',
  BigInt: 'number',
  Float: 'number',
  Decimal: 'number',
  Boolean: 'boolean',
  DateTime: 'Date',
  Json: 'Record<string, unknown>',
  Bytes: 'Uint8Array',
}

const toTsType = (field, enums) => {
  const enumNames = enums.map((e) => e.name)

  let type

  if (enumNames.includes(field.type)) {
    type = field.type
  } else {
    type = PRISMA_TO_TS[field.type] ?? 'unknown'
  }

  if (field.isList) type = `${type}[]`
  if (!field.isRequired) type = `${type} | null`

  return type
}

generatorHandler({
  onManifest() {
    return {
      prettyName: 'Prisma Types Generator',
      defaultOutput: '../generated/prisma/types.ts',
    }
  },

  async onGenerate(options) {
    const { models, enums } = options.dmmf.datamodel

    const lines = [
      '/* !!! This is code generated by prisma-generator-ids. Do not edit directly. !!! */',
      '',
      '// ---------------------------------------------------------------------------',
      '// Flavor',
      '// ---------------------------------------------------------------------------',
      '',
      'type Flavor<T, F> = T & { _type?: F }',
      '',
    ]

    // IDs
    lines.push(
      '// ---------------------------------------------------------------------------',
      '// IDs',
      '// ---------------------------------------------------------------------------',
      '',
    )

    for (const model of models) {
      const idField = model.fields.find((f) => f.isId)
      if (!idField) continue

      const tsType = PRISMA_TO_TS[idField.type] ?? 'string'
      lines.push(
        `export type ${model.name}Id = Flavor<${tsType}, '__${model.name}Id'>`,
      )
    }

    // Enums
    lines.push(
      '',
      '// ---------------------------------------------------------------------------',
      '// Enums',
      '// ---------------------------------------------------------------------------',
      '',
    )

    for (const enumDef of enums) {
      lines.push(`export const ${enumDef.name} = {`)
      for (const value of enumDef.values) {
        lines.push(`  ${value.name}: '${value.name}',`)
      }
      lines.push('} as const')
      lines.push(
        `export type ${enumDef.name} = (typeof ${enumDef.name})[keyof typeof ${enumDef.name}]`,
      )
      lines.push('')
    }

    // Models
    lines.push(
      '// ---------------------------------------------------------------------------',
      '// Models',
      '// ---------------------------------------------------------------------------',
      '',
    )

    for (const model of models) {
      lines.push(`export type ${model.name} = {`)
      for (const field of model.fields) {
        if (field.relationName) continue // skip relation fields

        const isId = field.isId
        const tsType = isId ? `${model.name}Id` : toTsType(field, enums)

        lines.push(`  ${field.name}: ${tsType}`)
      }
      lines.push('}')
      lines.push('')
    }

    const outputPath = options.generator.output?.value
    if (!outputPath) throw new Error('No output path specified')

    fs.mkdirSync(path.dirname(outputPath), { recursive: true })
    fs.writeFileSync(outputPath, `${lines.join('\n')}\n`)
  },
})
